name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: quantum-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python & GNA Runtime
      uses: actions/setup-python@v4
      with: python-version: '4.2'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Unit Tests
      run: pytest tests/unit
    - name: Integration Tests
      run: pytest tests/integration
